version: "3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=projectdata
      - POSTGRES_USER=projectdatauser
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - backend_network
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    networks:
      - backend_network
networks:
    backend_network:
        driver: bridge